# Generated by Django 4.0.4 on 2022-05-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlg_user_id', models.CharField(max_length=50, verbose_name='ID пользователя телеграмма')),
                ('tlg_user_name', models.CharField(max_length=50, verbose_name='Имя пользователя телеграмма')),
                ('processing_status', models.BooleanField(default=False, verbose_name='Статус обработки')),
                ('application_text', models.CharField(max_length=1000, verbose_name='Текст заявок')),
            ],
            options={
                'verbose_name': 'Заявки',
                'verbose_name_plural': 'Заявки',
                'db_table': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='CompletedWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=50, verbose_name='Название работы')),
                ('result_price', models.FloatField(verbose_name='Итоговая цена работы')),
                ('work_description', models.CharField(max_length=1000, verbose_name='Описание работы')),
            ],
            options={
                'verbose_name': 'Выполненная работа',
                'verbose_name_plural': 'Выполненные работы',
                'db_table': 'Выполненные работы',
            },
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Название категории работ')),
            ],
            options={
                'verbose_name': 'Категория работ',
                'verbose_name_plural': 'Категории работ',
                'db_table': 'Категории работ',
            },
        ),
        migrations.CreateModel(
            name='MediaFilesForCompletedWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(blank=True, max_length=2000, null=True, upload_to='files/%Y/%m/%d')),
                ('for_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tlg_bot.completedworks')),
            ],
        ),
        migrations.AddField(
            model_name='completedworks',
            name='work_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlg_bot.workcategory'),
        ),
    ]
