# Generated by Django 4.0.4 on 2022-05-25 14:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tlg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата заявки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedworks',
            name='date_of_completion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата выполнения работы'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='mediafilesforcompletedworks',
            table='Медиа работ',
        ),
    ]
