# Generated by Django 4.0.4 on 2022-05-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlg_bot', '0002_applications_date_completedworks_date_of_completion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='application_text',
            field=models.TextField(max_length=1000, verbose_name='Текст заявок'),
        ),
        migrations.AlterField(
            model_name='completedworks',
            name='work_description',
            field=models.TextField(max_length=1000, verbose_name='Описание работы'),
        ),
    ]
