# Generated by Django 4.0.4 on 2022-05-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlg_bot', '0004_alter_workcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['-id'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='completedworks',
            options={'ordering': ['-id'], 'verbose_name': 'Выполненная работа', 'verbose_name_plural': 'Выполненные работы'},
        ),
        migrations.AlterModelOptions(
            name='mediafilesforcompletedworks',
            options={'ordering': ['-id']},
        ),
    ]
