# Generated by Django 4.0.4 on 2022-05-25 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlg_bot', '0005_alter_applications_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['id'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='completedworks',
            options={'ordering': ['id'], 'verbose_name': 'Выполненная работа', 'verbose_name_plural': 'Выполненные работы'},
        ),
        migrations.AlterModelOptions(
            name='mediafilesforcompletedworks',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='workcategory',
            options={'ordering': ['id'], 'verbose_name': 'Категория работ', 'verbose_name_plural': 'Категории работ'},
        ),
    ]
