# Generated by Django 4.0.4 on 2022-05-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlg_bot', '0006_alter_applications_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applications',
            options={'ordering': ['id'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
