# Generated by Django 4.0.4 on 2022-05-27 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tlg_bot', '0007_alter_applications_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedworks',
            name='work_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tlg_bot.workcategory', verbose_name='Категория работ'),
        ),
    ]
